name: Issue Reminder

on:
  schedule:
    - cron: "0 9 * * *" # Runs daily at 9 AM UTC

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Reminder Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash
          echo "Running issue reminder..."
          # Example: List issues with a specific label or milestone (customize as needed)
          gh issue list --label "overdue" || echo "No overdue issues."
          # You can also add your custom logic here to send emails or Slack messages.
